source 'https://rubygems.org'
gem 'rails', '4.1.7'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'backbone-on-rails'
# gem 'bcrypt', '~> 3.1.7'
group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end
