# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbef0fba0c3ae2430db450896c0f8f166fdf24fd56417fc1e79de5ff57e28bf43af289d7c8813816b400f7adc3287eccde2951cea84b796e11911f900f1acfb

test:
  secret_key_base: dbcd0118435ed42395514618c1fb97503b305a8b4f3e0df3e9359480e9f1179a40a7494f84b9baad04a5ad98ecba9c59489a2cc0922bcec6e7a2e8c891ae26e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
